"""
add tariff is trial and is popular fields

Revision ID: a61b81e48c09
Revises: ee832a0b2a11  # noqa: UP035
Create Date: 2026-02-22 10:58:21.354528

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a61b81e48c09"
down_revision: str | None = "ee832a0b2a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariff",
        sa.Column(
            "is_trial",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "tariff",
        sa.Column(
            "is_popular",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariff", "is_popular")
    op.drop_column("tariff", "is_trial")
    # ### end Alembic commands ###
