"""
add xui sub id

Revision ID: 4f44d8ab82ae
Revises: 8952ecc037be  # noqa: UP035
Create Date: 2026-02-23 18:25:21.226983

"""

from typing import Sequence  # noqa: UP035

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4f44d8ab82ae"
down_revision: str | None = "8952ecc037be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("xui_sub_id", sa.String(length=32), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_user_xui_sub_id"), "user", ["xui_sub_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_xui_sub_id"), "user", type_="unique")
    op.drop_column("user", "xui_sub_id")
    # ### end Alembic commands ###
