"""
fix cookie length

Revision ID: 8952ecc037be
Revises: 68027421afdc  # noqa: UP035
Create Date: 2026-02-22 20:29:29.871611

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8952ecc037be"
down_revision: str | None = "68027421afdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server",
        "cookie",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server",
        "cookie",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
