"""
add user phone, user email, tariff order index

Revision ID: 6be801b961be
Revises: 1fc36acdae3b  # noqa: UP035
Create Date: 2026-02-21 15:32:29.883486

"""

from typing import Sequence  # noqa: UP035

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6be801b961be"
down_revision: str | None = "1fc36acdae3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariff",
        sa.Column(
            "order_index", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "user", sa.Column("email", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "user", sa.Column("phone", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone")
    op.drop_column("user", "email")
    op.drop_column("tariff", "order_index")
    # ### end Alembic commands ###
