"""
add lead

Revision ID: f0fe3f68da1c
Revises: 6be801b961be  # noqa: UP035
Create Date: 2026-02-21 18:31:09.919509

"""

from typing import Sequence  # noqa: UP035

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f0fe3f68da1c"
down_revision: str | None = "6be801b961be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
