"""
telegram_id set unique and not null

Revision ID: 68027421afdc
Revises: a61b81e48c09  # noqa: UP035
Create Date: 2026-02-22 15:06:46.594439

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68027421afdc"
down_revision: str | None = "a61b81e48c09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_user_telegram_id"), "user", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_telegram_id"), "user", type_="unique")
    # ### end Alembic commands ###
