SUPPORT_BUTTON_TEXT = "Поддержка 🛠"
LK_BUTTON_TEXT = "Личный кабинет 🔐"
FEEDBACK_BUTTON_TEXT = "Отзывы о нас 📌"
REFERRAL_BUTTON_TEXT = "Реферальная программа 🆓"

NOTIFICATION_SERVER_FULL = "⚠️<b>WARNING!</b>⚠️\n\nВсе места на серверах закончились"

LIMIT_TOTAL_USERS_ON_SERVER = 10
LIMIT_ACTIVE_USERS_ON_SERVER = 10

PAGINATION_LIMIT_ADMIN_LIST_LEADS = 5
PAGINATION_OFFSET_ADMIN_LIST_LEADS = 0
